# Generated by Django 4.1 on 2022-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("lokasi", models.TextField()),
                (
                    "jenis",
                    models.TextField(
                        choices=[
                            ("Musik", "Musik"),
                            ("Olahraga", "Olahraga"),
                            ("Budaya", "Budaya"),
                            ("Lainnya", "Lainnya"),
                        ],
                        default=None,
                    ),
                ),
                ("deskripsi", models.TextField()),
                ("foto", models.URLField(null=True)),
            ],
        ),
    ]
