# Generated by Django 4.1 on 2022-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='event',
            name='username',
        ),
    ]
