# Generated by Django 4.1 on 2022-10-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jenis',
            field=models.TextField(choices=[('Atraksi', 'Atraksi'), ('Konser', 'Konser'), ('Olahraga', 'Olahraga'), ('Tur', 'Tur')], default=None),
        ),
    ]
