# Generated by Django 4.1 on 2022-10-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_event', '0002_alter_event_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jenis',
            field=models.TextField(choices=[('Musik', 'Musik'), ('Olahraga', 'Olahraga'), ('Budaya', 'Budaya'), ('Lainnya', 'Lainnya')], default=None),
        ),
    ]
