# Generated by Django 4.1 on 2022-10-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_event', '0002_remove_event_foto_remove_event_username'),
        ('daftar_event', '0003_alter_event_jenis'),
    ]

    operations = [
    ]
