# Generated by Django 4.1 on 2022-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_event', '0004_merge_20221029_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='foto',
            field=models.URLField(null=True),
        ),
    ]
