# Generated by Django 4.1 on 2022-11-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_event', '0005_event_created_by_event_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
