# Generated by Django 4.1 on 2022-10-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destinasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("lokasi", models.TextField()),
                ("kategori", models.CharField(max_length=100)),
                ("foto_thumbnail_url", models.URLField()),
                ("foto_cover_url", models.URLField()),
                ("maps_url", models.URLField()),
                ("suka", models.IntegerField(default=0)),
            ],
        ),
    ]
